### ISSUE TITLE
Error at step 4

### ISSUE THREAD

**Issue by Silentbison** [philtsip/aisdr#2]
I've followed the README. 
At step 4 when I Run it gives me this notice in the execution log:
```
Notice Execution started
Error TypeError: Cannot read properties of undefined (reading 'toLowerCase')
cleanContact @  Code.gs:44
```

which is this block: 
```
function cleanContact(str) {
  if (
    str.toLowerCase().includes("not provided") ||
    str.toLowerCase().includes("not available") ||
    str.toLowerCase().includes("not applicable")
  ) {
    return "";
  }
```
I also tried adding the code manually. When clicking Run i got this error in the execution log:

`Error Attempted to execute cleanContact, but it was deleted.`

What am I missing?

**Comment by philtsip** [comment]
It’s a little hard to tell from just this.

This bit tries to clean up the formatting of the found contact. But you don’t have a found contact.

So it lets you know that.

**Comment by Silentbison** [comment]
It must be because I was running it from the AppScript editor, as Step 4 directed, rather than selecting the input field and running the macro from the sheet. I think this is resolved, I just wasn't expecting an error on Step 4 so I didn't continue to Step 5.
